name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2
      - run: bun install --frozen-lockfile
      - run: bunx prisma generate
        env:
          # Dummy URL; generation does not connect to DB
          DATABASE_URL: postgresql://postgres:postgres@localhost:5432/postgres?schema=public

      # checks
      - run: bun run check
      - run: bun run build

